---
- name: Configure /etc/crontab
  file:
    state: file
    path: /etc/crontab
    owner: root
    group: root
    mode: '0600'

- name: Create /etc/cron.hourly
  file:
    state: directory
    path: /etc/cron.hourly
    owner: root
    group: root
    mode: '0700'

- name: Create /etc/cron.daily
  file:
    state: directory
    path: /etc/cron.daily
    owner: root
    group: root
    mode: '0700'

- name: Create /etc/cron.weekly
  file:
    state: directory
    path: /etc/cron.weekly
    owner: root
    group: root
    mode: '0700'

- name: Create /etc/cron.monthly
  file:
    state: directory
    path: /etc/cron.monthly
    owner: root
    group: root
    mode: '0700'

- name: Create /etc/cron.d
  file:
    state: directory
    path: /etc/cron.d
    owner: root
    group: root
    mode: '0700'

- name: Remove /etc/cron.deny
  file:
    state: absent
    path: /etc/cron.deny

- name: Remove /etc/at.deny
  file:
    state: absent
    path: /etc/at.deny

- name: Check existence of /etc/cron.allow
  stat:
    path: /etc/cron.allow
  register: __cron_allow_file

- name: Configure /etc/cron.allow
  file:
    state: touch
    path: /etc/cron.allow
    owner: root
    group: root
    mode: '0640'
  when:
    - __cron_allow_file.stat.exists is defined
    - not __cron_allow_file.stat.exists 

- name: Check existence of /etc/at.allow
  stat:
    path: /etc/at.allow
  register: __at_allow_file

- name: Configure /etc/at.allow
  file:
    state: touch
    path: /etc/at.allow
    owner: root
    group: root
    mode: '0640'
  when:
    - __at_allow_file.stat.exists is defined
    - not __at_allow_file.stat.exists 
